### ISSUE TITLE
/api/users returns preferredColour whereas /api/users/{user} returns preferredColor

### ISSUE THREAD

**Issue by arman-izadi-1** [kartoffelquadrat/LobbyService#3]
Hello, 

When running GET on api/users to get all the users in the LS the attribute is spelled as preferredColour whereas when running a GET on a specific user to get info on that one user, the attribute is spelled as preferredColor. 

This causes issues when trying to save the User information as an object and to reconcile the two requests.

**Comment by m5c** [comment]
Thanks! Changed it to the Canadian spelling "preferredColour", with 'u'.
