### ISSUE TITLE
"+" is being removed the the access token of users whenever we send a request with it

### ISSUE THREAD

**Issue by TamPhilip** [kartoffelquadrat/LobbyService#4]
Whenever we post a request with an access token with the character + it is removed and sends an error of invalid_token.
This only happens when it is sent as a query string. 

Example request in python:
```python
token = "o5dzRnobJ3fIC666Ibg79+QqnO8="
users = requests.get('YOUR_URL/api/users?access_token={}'.format(token))

```
<img width="825" alt="Screen Shot 2021-04-14 at 8 11 48 PM" src="https://user-images.githubusercontent.com/32284547/114795879-a58e0700-9d5d-11eb-872a-8f1e24c73495.png">

**Comment by m5c** [comment]
The plus sign can not be used in query parameters. You have to escape it. Replace the "+" by "%2B". See lecture.
