### ISSUE TITLE
Able to create user with no special characters in password

### ISSUE THREAD

**Issue by arman-izadi-1** [kartoffelquadrat/LobbyService#5]
Hello,

Despite password policy of the LS, I was able to successfully create a user with the following JSON body: 
```
{
    "name": "arman1",
    "password": "ABCabc123456",
    "preferredColour": "01FFFF",
    "role": "ROLE_PLAYER"
}
```

This returns status code 200 OK despite not adhering to password policy.

**Comment by m5c** [comment]
Thanks!
Fixed by [commit 2a655405981ec02d7e36d5193ede232f6bb71512](https://github.com/kartoffelquadrat/LobbyService/commit/2a655405981ec02d7e36d5193ede232f6bb71512).
